In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
275234,166437.0,-0.619418,0.822471,-0.818036,1.300766,1.836554,-0.649880,1.963013,-0.438465,-1.168854,...,0.098205,0.291522,-0.099331,-0.598198,0.374619,-0.364733,-0.045905,-0.015786,158.0,0.0
275235,166437.0,-0.966986,0.015744,1.786483,-2.984102,-1.301897,-0.486245,-0.720859,0.485952,-2.062750,...,-0.328532,-0.575590,-0.171412,-0.136203,0.377049,-0.347791,0.182100,0.056142,5.0,0.0
275236,166438.0,1.799803,-2.314789,-0.715295,-1.461901,-1.766602,-0.037490,-1.317248,-0.038556,-1.102614,...,0.267159,0.803152,-0.133821,-0.457007,-0.246877,0.024098,-0.002014,-0.015371,249.0,0.0
275237,166438.0,1.945100,0.464009,-2.296450,1.384582,1.081907,-0.637361,0.641580,-0.232088,-0.239765,...,0.035312,0.258559,-0.024747,0.600258,0.460521,-0.546479,-0.004511,-0.026952,28.3,0.0
275238,166438.0,2.036473,-0.021870,-1.085398,0.500278,-0.106741,-1.226224,0.187898,-0.399751,0.320678,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275239 entries, 0 to 275238
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    275239 non-null  float64
 1   V1      275239 non-null  float64
 2   V2      275239 non-null  float64
 3   V3      275239 non-null  float64
 4   V4      275239 non-null  float64
 5   V5      275239 non-null  float64
 6   V6      275239 non-null  float64
 7   V7      275239 non-null  float64
 8   V8      275239 non-null  float64
 9   V9      275239 non-null  float64
 10  V10     275239 non-null  float64
 11  V11     275239 non-null  float64
 12  V12     275239 non-null  float64
 13  V13     275239 non-null  float64
 14  V14     275239 non-null  float64
 15  V15     275239 non-null  float64
 16  V16     275239 non-null  float64
 17  V17     275238 non-null  float64
 18  V18     275238 non-null  float64
 19  V19     275238 non-null  float64
 20  V20     275238 non-null  float64
 21  V21     275238 non-null  float64
 22  V22     275238 non-null  float64
 23  V23     275238 non-null  float64
 24  V24     275238 non-null  float64
 25  V25     275238 non-null  float64
 26  V26     275238 non-null  float64
 27  V27     275238 non-null  float64
 28  V28     275238 non-null  float64
 29  Amount  275238 non-null  float64
 30  Class   275238 non-null  float64
dtypes: float64(31)
memory usage: 65.1 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    274754
1.0       484
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(274754, 31)
(484, 31)

In [10]:
# statistical measures of the data
legit.Amount.describe()

count    274754.000000
mean         89.037575
std         251.545313
min           0.000000
25%           5.880000
50%          22.440000
75%          78.000000
max       25691.160000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count     484.000000
mean      120.595992
std       257.053306
min         0.000000
25%         1.000000
50%         8.770000
75%       104.225000
max      2125.870000
Name: Amount, dtype: float64

In [12]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,92245.349771,0.004567,-0.017029,0.039530,-0.002667,-0.005247,0.007257,0.005413,-0.001740,0.004666,...,-0.000092,-0.001449,-0.002747,-0.001362,0.000261,0.005113,-0.000100,-0.000156,0.000146,89.037575
1.0,79293.849174,-4.843268,3.672953,-7.095002,4.599361,-3.194524,-1.408096,-5.651005,0.580155,-2.609053,...,0.372818,0.722445,0.010374,-0.042890,-0.108396,0.041991,0.050101,0.167323,0.076402,120.595992

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 484

In [18]:
legit_sample = legit.sample(n=484)

# Concatenating two DataFrames

In [19]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [20]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
224642,143893.0,-0.601109,-0.083612,0.329126,-1.380493,-0.292795,-0.399559,-0.271460,0.562152,-0.817015,...,-0.729715,-2.025746,0.430405,0.323553,-1.197542,-0.039313,0.009579,0.089014,28.16,0.0
51389,44922.0,0.827244,-1.073171,0.449825,0.226623,-0.959785,0.126206,-0.391612,0.027222,0.965510,...,0.151923,0.047748,-0.357992,-0.472335,0.249946,1.143140,-0.083123,0.047121,248.00,0.0
102728,68334.0,1.201119,0.096247,-0.006789,0.525922,-0.163202,-0.733983,0.205734,-0.130913,0.032841,...,-0.030541,-0.112737,-0.034487,0.106508,0.437211,0.502855,-0.053258,0.003104,26.90,0.0
24463,33249.0,1.320544,-0.650502,0.046755,-0.669168,-0.719141,-0.325773,-0.525902,0.058855,-0.833186,...,0.220769,0.609064,-0.140521,0.048764,0.640740,-0.049900,-0.006579,-0.010684,20.00,0.0
28589,35066.0,-0.828537,0.876200,0.857566,-1.002114,-0.382132,-0.939743,0.134101,0.531758,-0.324036,...,0.227305,0.525880,-0.084804,0.376039,-0.501044,0.882074,0.166075,0.124352,0.67,0.0

In [21]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
263877,161154.0,-3.387601,3.977881,-6.978585,1.657766,-1.100500,-3.599487,-3.686651,1.942252,-3.065089,...,1.043587,0.262189,-0.479224,-0.326638,-0.156939,0.113807,0.354124,0.287592,0.38,1.0
268375,163181.0,-5.238808,0.623013,-5.784507,1.678889,-0.364432,-0.477295,-4.276132,-0.695173,-2.971644,...,-0.326140,1.509239,-0.215966,-0.245727,0.893041,0.865758,0.854657,-0.964482,39.98,1.0
272521,165132.0,-7.503926,-0.360628,-3.830952,2.486103,2.497367,1.332437,-6.783964,-15.415385,0.465512,...,-6.389132,2.249964,1.670508,0.140450,0.162147,1.207731,1.268958,0.097538,12.31,1.0
274382,165981.0,-5.766879,-8.402154,0.056543,6.950983,9.880564,-5.773192,-5.748879,0.721743,-1.076274,...,0.880395,-0.130436,2.241471,0.665346,-1.890041,-0.120803,0.073269,0.583799,0.00,1.0
274475,166028.0,-0.956390,2.361594,-3.171195,1.970759,0.474761,-1.902598,-0.055178,0.277831,-1.745854,...,0.473211,0.719400,0.122458,-0.255650,-0.619259,-0.484280,0.683535,0.443299,39.90,1.0

In [22]:
new_dataset['Class'].value_counts()

Class
0.0    484
1.0    484
Name: count, dtype: int64

In [23]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,90748.212810,-0.016486,-0.036716,0.056105,0.106401,-0.036375,0.039231,-0.066982,0.053624,0.042146,...,0.026235,0.059147,-0.030575,-0.00226,-0.002415,0.013131,0.001254,0.028811,0.011647,100.506095
1.0,79293.849174,-4.843268,3.672953,-7.095002,4.599361,-3.194524,-1.408096,-5.651005,0.580155,-2.609053,...,0.372818,0.722445,0.010374,-0.04289,-0.108396,0.041991,0.050101,0.167323,0.076402,120.595992

In [24]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [25]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
224642  143893.0 -0.601109 -0.083612  0.329126 -1.380493 -0.292795 -0.399559
51389    44922.0  0.827244 -1.073171  0.449825  0.226623 -0.959785  0.126206
102728   68334.0  1.201119  0.096247 -0.006789  0.525922 -0.163202 -0.733983
24463    33249.0  1.320544 -0.650502  0.046755 -0.669168 -0.719141 -0.325773
28589    35066.0 -0.828537  0.876200  0.857566 -1.002114 -0.382132 -0.939743
...          ...       ...       ...       ...       ...       ...       ...
263877  161154.0 -3.387601  3.977881 -6.978585  1.657766 -1.100500 -3.599487
268375  163181.0 -5.238808  0.623013 -5.784507  1.678889 -0.364432 -0.477295
272521  165132.0 -7.503926 -0.360628 -3.830952  2.486103  2.497367  1.332437
274382  165981.0 -5.766879 -8.402154  0.056543  6.950983  9.880564 -5.773192
274475  166028.0 -0.956390  2.361594 -3.171195  1.970759  0.474761 -1.902598

              V7         V8        V9  ...       V20       V21       V22  \
224642 -0.271460   0.562152 -0.817015  ... -0.642963 -0.729715 -2.025746
51389  -0.391612   0.027222  0.965510  ...  0.452949  0.151923  0.047748
102728  0.205734  -0.130913  0.032841  ... -0.145479 -0.030541 -0.112737
24463  -0.525902   0.058855 -0.833186  ... -0.035802  0.220769  0.609064
28589   0.134101   0.531758 -0.324036  ... -0.157793  0.227305  0.525880
...          ...        ...       ...  ...       ...       ...       ...
263877 -3.686651   1.942252 -3.065089  ... -0.004301  1.043587  0.262189
268375 -4.276132  -0.695173 -2.971644  ... -0.203270 -0.326140  1.509239
272521 -6.783964 -15.415385  0.465512  ... -0.475126 -6.389132  2.249964
274382 -5.748879   0.721743 -1.076274  ...  2.493224  0.880395 -0.130436
274475 -0.055178   0.277831 -1.745854  ...  0.190877  0.473211  0.719400

             V23       V24       V25       V26       V27       V28  Amount
224642  0.430405  0.323553 -1.197542 -0.039313  0.009579  0.089014   28.16
51389  -0.357992 -0.472335  0.249946  1.143140 -0.083123  0.047121  248.00
102728 -0.034487  0.106508  0.437211  0.502855 -0.053258  0.003104   26.90
24463  -0.140521  0.048764  0.640740 -0.049900 -0.006579 -0.010684   20.00
28589  -0.084804  0.376039 -0.501044  0.882074  0.166075  0.124352    0.67
...          ...       ...       ...       ...       ...       ...     ...
263877 -0.479224 -0.326638 -0.156939  0.113807  0.354124  0.287592    0.38
268375 -0.215966 -0.245727  0.893041  0.865758  0.854657 -0.964482   39.98
272521  1.670508  0.140450  0.162147  1.207731  1.268958  0.097538   12.31
274382  2.241471  0.665346 -1.890041 -0.120803  0.073269  0.583799    0.00
274475  0.122458 -0.255650 -0.619259 -0.484280  0.683535  0.443299   39.90

[968 rows x 30 columns]

In [26]:
print(Y)

224642    0.0
51389     0.0
102728    0.0
24463     0.0
28589     0.0
         ...
263877    1.0
268375    1.0
272521    1.0
274382    1.0
274475    1.0
Name: Class, Length: 968, dtype: float64

Split the data into Training data & Testing Data

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [28]:
print(X.shape, X_train.shape, X_test.shape)

(968, 30) (774, 30) (194, 30)

# Model Training

# Logistic Regression

In [29]:
model = LogisticRegression()

In [30]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [31]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [32]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9560723514211886

In [33]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [34]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9587628865979382